
##
# vscode rest client extension http file
# see https://github.com/Huachao/vscode-restclient
# use ### to separate requests
##

##
#
# cert setup. place in vscode 'setttings.json'
#"rest-client.certificates": {
#     "%fqdn%: {
#         "pfx": "%path to pfx file%",
#         "passphrase": ""
#     }
# },
##

##
# azure aadv1 setup
#
# "rest-client.environmentVariables": {
#     "$shared": {
#         "subscriptionId": "",
#         "tenantId": ""
#     }
# }
##

# ip info
https://ipinfo.io/json
###

# sf package download versions
https://go.microsoft.com/fwlink/?LinkID=824848&clcid=0x409
###

###
GET https://api.github.com/repos/microsoft/CollectServiceFabricData/releases/latest


# github api urls
https://api.github.com
###

# github repo views query
# @name repoViewsQuery
@gitToken = 
#https://api.github.com/repos/jagilber/powershellscripts/traffic/views
https://api.github.com/repos/jagilber/powershellscripts/traffic/popular/paths
Authorization: Bearer {{gitToken}}
Accept: application/vnd.github+json
X-GitHub-Api-Version: 2022-11-28
###

# github repo query
# @name repoQuery
https://api.github.com/repos/jagilber/powershellscripts
###
@forks = {{repoQuery.response.body.$.forks_url}}
GET {{forks}}
###
@downloads = {{repoQuery.response.body.$.downloads_url}}
GET {{downloads}}
###

https://www.w3.org/services/html2txt?url=https://store.rg-adguard.net/api/GetFiles?type=url&url=https://www.microsoft.com/store/apps/9pgjgd53tn86
###

###
# convert google news to text
https://www.w3.org/services/html2txt?url=https://news.google.com 
###

# nuget api test
@id = https://azuresearch-usnc.nuget.org/query
@QUERY = Microsoft.ServiceFabric.CollectSFData
@SKIP = 0
@TAKE = 10
@PRERELEASE = false
#@SEMVERLEVEL = {{}}
#@PACKAGETYPE = {{}}
GET {{id}}?q={{QUERY}}&skip={{SKIP}}&take={{TAKE}}&prerelease={{PRERELEASE}}
#&semVerLevel={SEMVERLEVEL}&packageType={PACKAGETYPE}

###
GET https://www.w3.org/services/html2txt?url=https://devblogs.microsoft.com/powershell/arm-dsc-extension-settings/
###


###
# SFRP
@cluster = sfjagilber1lx3
@location = eastus
@api = 6.0
@managementPort = 19080
@timeout = 1200
#https://{{cluster}}.{{location}}.cloudapp.azure.com:19080/$/BackupRestore/BackupPolicies?api-version={{api}}

#https://{{cluster}}.{{location}}.cloudapp.azure.com:19080/Applications/?api-version={{api}}
https://{{cluster}}.{{location}}.cloudapp.azure.com:19080/$/GetClusterManifest?api-version={{api}}&timeout={{timeout}} HTTP/1.1
#https://{{cluster}}.{{location}}.cloudapp.azure.com:{{managementPort}}/$/GetClusterHealth?api-version={{api}}
#https://{{cluster}}.{{location}}.cloudapp.azure.com:19080/Nodes/?api-version={{api}} HTTP/1.1
Accept: application/xml,application/json

#GET https://{{cluster}}.{{location}}.cloudapp.azure.com:{{managementPort}}/Explorer
###

###
@storageAccountName = sflogsxxxxxxxxxxxxxxxxxx
@tableSasToken = ?sv=2020-02-10&ss=bfqt&srt=sco&sp=rwdlacupx&se=2021-03-25T10:16:34Z&st=2021-03-25T02:16:34Z&spr=https&sig=DEIyaWBlIKe0Nru1ubEbb6u5t787LwoqQ5UVWgxMoJQ%3D
@storageObjectToQuery = fabriclog8de7b13a4137454a9ad5a356fa0c3159Api
https://{{storageAccountName}}.table.core.windows.net/{{storageObjectToQuery}}{{tableSasToken}}

###
GET https://localhost:5001/api/configurationJson HTTP/1.1
content-type: application/json

###
GET https://localhost:5001/api/configurationOptions HTTP/1.1
content-type: application/json

###
GET https://localhost:5001/api/configuration HTTP/1.1
content-type: application/json


###
POST https://localhost:5001/api/configuration/update HTTP/1.1
content-type: application/json

{
  "$schema": "https://raw.githubusercontent.com/microsoft/CollectServiceFabricData/master/configurationFiles/collectsfdata.schema.json",
  "AzureClientId": null,
  "AzureClientSecret": null,
  "AzureResourceGroup": null,
  "AzureResourceGroupLocation": null,
  "AzureSubscriptionId": null,
  "AzureTenantId": null,
  "CacheLocation": null,
  "ContainerFilter": null,
  "DeleteCache": false,
  "EndTimeStamp": "04/09/2021 21:46 -04:00",
  "GatherType": "trace",
  "KustoCluster": "https://ingest-sfus.kusto.windows.net/dblogs",
  "KustoCompressed": true,
  "KustoPurge": null,
  "KustoRecreateTable": false,
  "KustoTable": "jagilber_test",
  "KustoUseBlobAsSource": true,
  "KustoUseIngestMessage": false,
  "List": false,
  "LogAnalyticsCreate": false,
  "LogAnalyticsId": null,
  "LogAnalyticsKey": null,
  "LogAnalyticsName": null,
  "LogAnalyticsPurge": null,
  "LogAnalyticsRecreate": false,
  "LogAnalyticsWorkspaceName": null,
  "LogAnalyticsWorkspaceSku": "PerGB2018",
  "LogDebug": 4,
  "LogFile": null,
  "NodeFilter": null,
  "NoProgressTimeoutMin": 10,
  "ResourceUri": null,
  "SasKey": "https://sflogsxxxxxxxxxxxxx.blob.core.windows.net/?sv=2019-07-07&sig=iifcH%2B6%2FZwrea9w%2BWwp52nYFvyvxl7NVjRxWCyLKKSw%3D&spr=https&st=2021-04-11T01%3A47%3A51Z&se=2021-04-11T09%3A48%3A51Z&srt=sco&ss=bfqt&sp=racupwdl",
  "StartTimeStamp": "04/09/2021 19:46 -04:00",
  "Threads": 12,
  "Unique": true,
  "UriFilter": null,
  "UseMemoryStream": true,
  "UseTx": false,
  "Version": "${Process.GetCurrentProcess().MainModule?.FileVersionInfo.FileVersion}"
}

###
@storageAccountName = 
@tableSasToken = 
@storageObjectToQuery = 
https://{{storageAccountName}}.table.core.windows.net/{{storageObjectToQuery}}{{tableSasToken}}
###

###
# arm query
@query =
@apiversion = 2021-01-01
GET https://management.azure.com/subscriptions/{{subscriptionId}}/{{query}}?api-version={{apiversion}}
Authorization: {{$aadToken}}
Accept: application/json
###

###
# sfrp query api list
# https://docs.microsoft.com/en-us/rest/api/servicefabric/sfrp-api-operations_list
@query = providers/Microsoft.ServiceFabric/operations
@apiversion = 2018-02-01

GET https://management.azure.com/{{query}}?api-version={{apiversion}}
#GET https://management.azure.com/subscriptions/{{subscriptionId}}/{{query}}?api-version={{apiversion}}
Authorization: {{$aadToken}}
Accept: application/json
###

###
# sfrp get cluster
# https://docs.microsoft.com/en-us/rest/api/servicefabric/sfrp-api-clusters_get

@query = providers/Microsoft.ServiceFabric/clusters/{{clusterName}}
@apiversion = 2018-02-01
@resourceGroupName = sfcluster
@clusterName = {{resourceGroupName}}

#GET https://management.azure.com/{{query}}?api-version={{apiversion}}

GET https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/{{query}}?api-version={{apiversion}}
Authorization: {{$aadToken}}
Accept: application/json

###
# sfrp get available cluster versions
# https://docs.microsoft.com/en-us/rest/api/servicefabric/clusterversions/list

@apiversion = 2018-02-01
@location = eastus

GET https://management.azure.com/subscriptions/{{subscriptionId}}/providers/Microsoft.ServiceFabric/locations/{{location}}/clusterVersions?api-version={{apiversion}}
Authorization: {{$aadToken}}
Accept: application/json


###
# sfrp get available cluster version
# https://docs.microsoft.com/en-us/rest/api/servicefabric/clusterversions/get

@apiversion = 2018-02-01
@location = eastus

@clusterVersion = 7.2.432.9590
GET https://management.azure.com/subscriptions/{{subscriptionId}}/providers/Microsoft.ServiceFabric/locations/{{location}}/clusterVersions/{{clusterVersion}}?api-version={{apiversion}}
Authorization: {{$aadToken}}
Accept: application/json

###

PUT  http://localhost:8080/api/Votes/dfff
###

GET  http://localhost:8080
###

GET  http://localhost:8080/api/Votes?c={{$timestamp}}
###

PUT http://localhost:19081/Voting/VotingData/api/VoteData/ddddd?PartitionKey=3&PartitionKind=Int64Range
###

PUT http://localhost:19964/Voting/VotingData/api/VoteData/ddddd?PartitionKey=3&PartitionKind=Int64Range


### 
https://supportaction-prod.northeurope.cloudapp.azure.com/swagger/index.html HTTP/1.1

### 
https://supportaction-prod.northeurope.cloudapp.azure.com/swagger/index.html

###
