
##
# vscode rest client extension http file
# see https://github.com/Huachao/vscode-restclient
# use ### to separate requests
##

##
#
# cert setup. place in vscode 'setttings.json'
#"rest-client.certificates": {
#     "%fqdn%: {
#         "pfx": "%path to pfx file%",
#         "passphrase": ""
#     }
# },
##

##
# azure aadv1 setup
#
# "rest-client.environmentVariables": {
#     "$shared": {
#         "subscriptionId": "",
#         "tenantId": ""
#     }
##

# ip info
https://ipinfo.io/json
###

# sf package download versions
https://go.microsoft.com/fwlink/?LinkID=824848&clcid=0x409
###

###
GET https://api.github.com/repos/microsoft/CollectServiceFabricData/releases/latest


# github api urls
https://api.github.com
###

# github repo query
# @name repoQuery
https://api.github.com/repos/jagilber/powershellscripts
###
@forks = {{repoQuery.response.body.$.forks_url}}
GET {{forks}}
###
@downloads = {{repoQuery.response.body.$.downloads_url}}
GET {{downloads}}
###
https://www.w3.org/services/html2txt?url=https://store.rg-adguard.net/api/GetFiles?type=url&url=https://www.microsoft.com/store/apps/9pgjgd53tn86
###

###
# convert google news to text
https://www.w3.org/services/html2txt?url=https://news.google.com 
###

# nuget api test
@id = https://azuresearch-usnc.nuget.org/query
@QUERY = Microsoft.ServiceFabric.CollectSFData
@SKIP = 0
@TAKE = 10
@PRERELEASE = false
#@SEMVERLEVEL = {{}}
#@PACKAGETYPE = {{}}
GET {{id}}?q={{QUERY}}&skip={{SKIP}}&take={{TAKE}}&prerelease={{PRERELEASE}}
#&semVerLevel={SEMVERLEVEL}&packageType={PACKAGETYPE}

###
GET https://www.w3.org/services/html2txt?url=https://devblogs.microsoft.com/powershell/arm-dsc-extension-settings/
###


###
@cluster = sfcluster
@location = eastus
@apiversion = 6.4
@managementPort = 19080
#https://{{cluster}}.{{location}}.cloudapp.azure.com:19080/$/BackupRestore/BackupPolicies?api-version={{apiversion}}

#https://{{cluster}}.{{location}}.cloudapp.azure.com:19080/Applications/?api-version={{apiversion}}
#https://{{cluster}}.{{location}}.cloudapp.azure.com:19080/$/GetClusterManifest?api-version={{apiversion}}
#https://{{cluster}}.{{location}}.cloudapp.azure.com:{{managementPort}}/$/GetClusterHealth?api-version={{apiversion}}
GET https://{{cluster}}.{{location}}.cloudapp.azure.com:{{managementPort}}/Explorer
###

###
@storageAccountName = sflogsbmnjfzoagi7jc2
@tableSasToken = ?sv=2020-02-10&ss=bfqt&srt=sco&sp=rwdlacupx&se=2021-03-25T10:16:34Z&st=2021-03-25T02:16:34Z&spr=https&sig=DEIyaWBlIKe0Nru1ubEbb6u5t787LwoqQ5UVWgxMoJQ%3D
@storageObjectToQuery = fabriclog8de7b13a4137454a9ad5a356fa0c3159Api
https://{{storageAccountName}}.table.core.windows.net/{{storageObjectToQuery}}{{tableSasToken}}
###

###
# arm query
@query =
@apiversion = 2021-01-01
GET https://management.azure.com/subscriptions/{{subscriptionId}}/{{query}}?api-version={{apiversion}}
Authorization: {{$aadToken}}
Accept: application/json
###

###
# sfrp query api list
# https://docs.microsoft.com/en-us/rest/api/servicefabric/sfrp-api-operations_list
@query = providers/Microsoft.ServiceFabric/operations
@apiversion = 2018-02-01

GET https://management.azure.com/{{query}}?api-version={{apiversion}}
#GET https://management.azure.com/subscriptions/{{subscriptionId}}/{{query}}?api-version={{apiversion}}
Authorization: {{$aadToken}}
Accept: application/json
###

###
# sfrp get cluster
# https://docs.microsoft.com/en-us/rest/api/servicefabric/sfrp-api-clusters_get

@query = providers/Microsoft.ServiceFabric/clusters/{{clusterName}}
@apiversion = 2018-02-01
@resourceGroupName = sfcluster
@clusterName = {{resourceGroupName}}

#GET https://management.azure.com/{{query}}?api-version={{apiversion}}

GET https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/{{query}}?api-version={{apiversion}}
Authorization: {{$aadToken}}
Accept: application/json

###

PUT  http://localhost:8080/api/Votes/dfff
###

GET  http://localhost:8080
###

GET  http://localhost:8080/api/Votes?c={{$timestamp}}
###

PUT http://localhost:19081/Voting/VotingData/api/VoteData/ddddd?PartitionKey=3&PartitionKind=Int64Range
###

PUT http://localhost:19964/Voting/VotingData/api/VoteData/ddddd?PartitionKey=3&PartitionKind=Int64Range