# vscode rest client extension http file
# see https://github.com/Huachao/vscode-restclient
# use ### to separate requests

# sf package download versions
https://go.microsoft.com/fwlink/?LinkID=824848&clcid=0x409
###

# collectsfdata releases
https://github.com/microsoft/collectservicefabricdata/releases/latest
###

# collectsfdata releases
https://github.com/microsoft/collectservicefabricdata/releases
###

# github api urls
https://api.github.com
###

# github repo query
# @name repoQuery
https://api.github.com/repos/jagilber/powershellscripts
###
@forks = {{repoQuery.response.body.$.forks_url}}
GET {{forks}}
###

https://www.w3.org/services/html2txt?url=https://store.rg-adguard.net/api/GetFiles?type=url&url=https://www.microsoft.com/store/apps/9pgjgd53tn86
###

###
POST https://store.rg-adguard.net/api/GetFiles?type=url&url=https://www.microsoft.com/store/apps/9pgjgd53tn86


